// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATgy9WxQCu__YTl8Q5GZHLus9yN10eg74',
    appId: '1:1051216715351:web:6b62bd03497aa006774d12',
    messagingSenderId: '1051216715351',
    projectId: 'todo-fire-2024',
    authDomain: 'todo-fire-2024.firebaseapp.com',
    storageBucket: 'todo-fire-2024.appspot.com',
    measurementId: 'G-RC8C1KL6MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3P4-fK1wUWpUemUCfZ1JeKLDIZr-abE',
    appId: '1:1051216715351:android:135a0c57022cf595774d12',
    messagingSenderId: '1051216715351',
    projectId: 'todo-fire-2024',
    storageBucket: 'todo-fire-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfvm4WyXZ_dil8InyF6hphci63znFV0gQ',
    appId: '1:1051216715351:ios:d7cc6dfce1ccb03c774d12',
    messagingSenderId: '1051216715351',
    projectId: 'todo-fire-2024',
    storageBucket: 'todo-fire-2024.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfvm4WyXZ_dil8InyF6hphci63znFV0gQ',
    appId: '1:1051216715351:ios:cf301b7603b0b5a2774d12',
    messagingSenderId: '1051216715351',
    projectId: 'todo-fire-2024',
    storageBucket: 'todo-fire-2024.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
